name: Rebase staging into main
on: [workflow_dispatch]

jobs:
  rebase-staging-into-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout main
        run: |
          git pull
          git checkout main
      - name: rebase staging into main
        run: git rebase staging
      - name: push main
        run: git push origin main

