name: Merge staging into main
on: [workflow_dispatch]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout main
        run: git checkout main
      - name: rabase staging into main
        run: git rebase staging
      - name: push main
        run: git push origin main

